name: Build
on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    steps:
      - name: checkout firmware
        uses: actions/checkout@v4
        with:
          # intentionally don't set it to "recursive" as zsa's submodules are managed via their Makefile.
          submodules: true

      - name: install dependencies
        run: /usr/bin/python3 -m pip install -r /__w/qmk_keymap/qmk_keymap/qmk_firmware/requirements.txt

      - name: copy keymap
        run: |
          cp -r eckig qmk_firmware/keyboards/zsa/voyager/keymaps/eckig
      - name: build keymap
        run: |
          cd qmk_firmware/keyboards/zsa/voyager/keymaps/eckig && qmk compile

      - uses: actions/upload-artifact@v4
        with:
          name: voyager.bin
          path: qmk_firmware/*.bin
